apiVersion: batch/v1
kind: Job
metadata:
  name: placeholder
spec:
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      restartPolicy: Never
  backoffLimit: 2
